### ISSUE TITLE
Ability to specify layout and semantic of groups of form fields.

### ISSUE THREAD

**Issue by jwfwessels** [praekelt/django-formfactory#14]
FormFactory (hear after FF) is missing some functionality that is key to the creating of fully fledged flexible forms via the CMS. 

This functionality will allow a content manager to group fields to create a 2 column or single column layout. Furthermore, for web accessability, it would be beneficial to group fields in a column into a field set with or without a legend (label)

To illustrate what I mean please look at the below image.

![untitled-1](https://cloud.githubusercontent.com/assets/1531788/21799760/480a5f48-d723-11e6-8778-de470a673806.png)

**Comment by qoda** [comment]
PR Created: https://github.com/praekelt/django-formfactory/pull/25
