### ISSUE TITLE
Support for custom error messages for each field

### ISSUE THREAD

**Issue by phala** [praekelt/django-formfactory#59]
With Django form fields, it is possible to add custom `error_messages` as discussed [in the docs](https://docs.djangoproject.com/en/1.10/ref/forms/fields/#error-messages).

There are cases where custom error messages will be needed for forms created with this app.

**Comment by qoda** [comment]
Would suggest using a new model with manytomany relationship to field (field specific errors) and form (general errors). the model would be:

```
class CustomErrorMessage(models.Model):
    key = models.CharField(max_length=128, choices=(("required", "required"), ("number", "number"), ...))
    value = models.CharField(max_length=256)
```

Than over-ride the original error message in `factory.py` using something along these lines:

```
Line 49:

self.fields[field.slug] = field_type(
    label=field.label,
    initial=field.initial or self.initial.get(field.slug),
    required=field.required,
    disabled=field.disabled,
    help_text=field.help_text,
    validators=additional_validators,
    error_messages=dict((m.key, m.value) for m in field.customfields.all())
)
```

**Comment by phala** [comment]
@qoda thanks for the suggestion! :+1:
